spring.application.name=adminContest

spring.datasource.url=jdbc:h2:file:./data/reservation_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=false

spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql

# JWT
jwt.secret=your-secret-key-must-be-at-least-256-bits-long-for-HS256-algorithm-change-this-in-production
jwt.expiration=86400000